### ISSUE TITLE
 add proxy configuration in yml

### ISSUE THREAD

**Issue by ODomWang** [Cormanz/smartgpt#18]
I hope to add proxy configuration in yml

**Comment by orvitpng** [comment]
I'll try to implement this after my new config work. Proxies can allow for higher security.

@ODomWang what type of protocols would you look for? Of course HTTP Proxy and SOCKS5 will be implemented, but I'm wondering what else you'd like to see.

**Comment by Cormanz** [comment]
That sounds good to me, ideally we should have some sort of global HTTP client settings that applies to all HTTP clients initialized in the project.

**Comment by ODomWang** [comment]
Because my region cannot directly access OpenAI and some APIs, I need to add a proxy in the HTTP request to facilitate network communication

**Comment by Cormanz** [comment]
Thanks for clarifying. We're planning to do a configuration overhaul soon, and we'll make sure that you can include a global proxy for requests during that update.

In the meantime, support for local LLMs is almost done and will be released shortly. Once added, if you choose to, you can try to load local models (although I can't guarantee results will be as good as GPT3.5)

**Comment by ODomWang** [comment]
Thank you for your patient response. I am looking forward to the next version now
